# Generated by Django 3.0 on 2021-05-21 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs_core', '0005_auto_20201031_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='bites',
            field=models.BooleanField(default=False, help_text='Whether dog bites'),
        ),
    ]
