# Generated by Django 3.0 on 2021-05-05 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sandwich',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bread', models.CharField(max_length=32)),
                ('filling', models.CharField(max_length=32)),
                ('mayo', models.BooleanField()),
                ('mustard', models.BooleanField()),
            ],
        ),
    ]
