# Generated by Django 3.0 on 2021-05-05 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toast', '0002_sandwich_horseradish'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sandwich',
            old_name='mayo',
            new_name='mayonnaise',
        ),
    ]
