# Generated by Django 3.0 on 2021-05-05 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toast', '0003_auto_20210505_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='sandwich',
            name='cheese',
            field=models.CharField(default='stilton', max_length=64),
            preserve_default=False,
        ),
    ]
