from django.urls import path, include
from rest_framework import routers
from . import views
from . import viewsets

app_name = 'api'

router = routers.DefaultRouter()
router.register(r'dogs', viewsets.DogsViewSet)
router.register(r'breeds', viewsets.BreedsViewSet)


urlpatterns = [
    # add the paths that are automatically generated by the
    # viewsets
    path('', include(router.urls)),

    # add path for function-based API view
    path('fbv/dogs', views.dogs, name="fbdogs"),

    # add paths for class-based API views
    # each model has two views, corresponding to
    # *resources* -- one with the primary key, and one
    # without

    # used with GET, provides list of Dog resources
    # used with POST, creates new resource
    path('cbv/dogs', views.DogsList.as_view(), name="dogs-cbv"),

    # used with GET, retrieves one Dog resource
    # used with PUT, replaces a Dog resource
    # used with PATCH, updates a Dog resource
    # used with DELETE, deletes a Dog resource
    path('cbv/dogs/<str:pk>', views.DogsDetail.as_view(), name="dogs-detail-cbv"),

    # same idea for Breed resources
    path('cbv/breeds', views.BreedsList.as_view(), name="breeds-cbv"),
    path('cbv/breeds/<str:pk>', views.BreedsDetail.as_view(), name="breeds-detail-cbv"),
]







