# Generated by Django 3.0 on 2021-05-06 13:07

from django.db import migrations, models
import django.db.models.deletion
import superheroes.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Enemy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Power',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('description', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Superhero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('real_name', models.CharField(default=superheroes.models.make_real_name, max_length=32)),
                ('secret_identity', models.CharField(max_length=32)),
                ('magic1', models.IntegerField(default=superheroes.models.get_random)),
                ('magic2', models.IntegerField(default=superheroes.models.get_random)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superheroes.City')),
                ('enemies', models.ManyToManyField(to='superheroes.Enemy')),
                ('powers', models.ManyToManyField(to='superheroes.Power')),
            ],
        ),
        migrations.AddField(
            model_name='enemy',
            name='powers',
            field=models.ManyToManyField(to='superheroes.Power'),
        ),
    ]
