# Generated by Django 3.0 on 2021-05-06 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superheroes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superhero',
            name='magic1',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='superhero',
            name='magic2',
            field=models.IntegerField(default=2),
        ),
    ]
