# Generated by Django 3.0 on 2021-05-06 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superheroes', '0002_auto_20210506_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='superhero',
            name='thing',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
