# Generated by Django 3.0 on 2021-05-06 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superheroes', '0003_superhero_thing'),
    ]

    operations = [
        migrations.AddField(
            model_name='superhero',
            name='x',
            field=models.IntegerField(default=42),
        ),
    ]
